services:
  distributor:
    build: .
    container_name: log-distributor
    ports:
      - "8080:8080"  # Emitter port
      - "8081:8081"  # Analyzer port
    networks:
      - log-network
    
  # Analyzers with different weights
  analyzer-1:
    build: .
    container_name: analyzer-1
    command: ["./analyzer", "-addr=distributor:8081", "-weight=0.4", "-id=analyzer-1", "-ack-every=5"]
    depends_on:
      - distributor
    networks:
      - log-network
    
  analyzer-2:
    build: .
    container_name: analyzer-2
    command: ["./analyzer", "-addr=distributor:8081", "-weight=0.3", "-id=analyzer-2", "-ack-every=5"]
    depends_on:
      - distributor
    networks:
      - log-network
      
  analyzer-3:
    build: .
    container_name: analyzer-3
    command: ["./analyzer", "-addr=distributor:8081", "-weight=0.2", "-id=analyzer-3", "-ack-every=5"]
    depends_on:
      - distributor
    networks:
      - log-network
    
  analyzer-4:
    build: .
    container_name: analyzer-4
    command: ["./analyzer", "-addr=distributor:8081", "-weight=0.1", "-id=analyzer-4", "-ack-every=5"]
    depends_on:
      - distributor
    networks:
      - log-network
    
  # Emitters generating load
  emitter-1:
    build: .
    container_name: emitter-1
    command: ["./emitter", "-addr=distributor:8080", "-rate=200", "-duration=300", "-id=emitter-1", "-size=512"]
    depends_on:
      - distributor
      - analyzer-1
      - analyzer-2
      - analyzer-3
      - analyzer-4
    networks:
      - log-network
    
  emitter-2:
    build: .
    container_name: emitter-2
    command: ["./emitter", "-addr=distributor:8080", "-rate=150", "-duration=300", "-id=emitter-2", "-size=256"]
    depends_on:
      - distributor
      - analyzer-1
      - analyzer-2
      - analyzer-3
      - analyzer-4
    networks:
      - log-network
    
  emitter-3:
    build: .
    container_name: emitter-3
    command: ["./emitter", "-addr=distributor:8080", "-rate=100", "-duration=300", "-id=emitter-3", "-size=1024"]
    depends_on:
      - distributor
      - analyzer-1
      - analyzer-2
      - analyzer-3
      - analyzer-4
    networks:
      - log-network

networks:
  log-network:
    driver: bridge